// Activate a logo concept and render the brand PNGs (favicons, apple-touch /
// PWA icons, OG image, README banner) with headless Chromium via Playwright.
//
//   node scripts/render-brand.mjs        # concept "a" (default, Singularity Q)
//   node scripts/render-brand.mjs b      # swap to concept B (Beacon)
//   node scripts/render-brand.mjs c      # swap to concept C (Orbit Badge)
//
// Activating a concept copies its SVGs over the default brand files that the
// app references (public/brand/logo.svg, favicon.svg, logo-lockup-*.svg and
// src/assets/logo.svg), then re-renders every PNG. Concept sources live in
// public/brand/concept-<a|b|c>-*.svg (generated by scripts/brand/gen-concepts.mjs).
import { chromium } from "../frontend/node_modules/playwright/index.mjs";
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const concept = (process.argv[2] || "a").toLowerCase();
if (!["a", "b", "c"].includes(concept)) throw new Error(`unknown concept "${concept}" (use a, b or c)`);

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pub = resolve(root, "frontend/public");
const brand = resolve(pub, "brand");
const docs = resolve(root, "docs/brand");
mkdirSync(docs, { recursive: true });

// 1) activate
const src = (k) => resolve(brand, `concept-${concept}-${k}.svg`);
copyFileSync(src("mark"), resolve(brand, "logo.svg"));
copyFileSync(src("icon"), resolve(brand, "favicon.svg"));
copyFileSync(src("lockup-dark"), resolve(brand, "logo-lockup-dark.svg"));
copyFileSync(src("lockup-light"), resolve(brand, "logo-lockup-light.svg"));
copyFileSync(src("mark"), resolve(root, "frontend/src/assets/logo.svg"));
writeFileSync(resolve(brand, "ACTIVE"), `${concept}\n`);
console.log("active concept:", concept);

const logo = readFileSync(resolve(brand, "logo.svg"), "utf8");
const icon = readFileSync(resolve(brand, "favicon.svg"), "utf8");
const lockup = readFileSync(resolve(brand, "logo-lockup-dark.svg"), "utf8");
const fontCss = (pkg, file) => pathToFileURL(resolve(root, "frontend/node_modules/@fontsource", pkg, file)).href;

const browser = await chromium.launch();
const page = await browser.newPage();

async function renderSvg(svg, size, out, bg = null) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(`<html><body style="margin:0;background:${bg ?? "transparent"}">${svg.replace("<svg ", `<svg width="${size}" height="${size}" style="display:block" `)}</body></html>`);
  await page.screenshot({ path: out, omitBackground: !bg, clip: { x: 0, y: 0, width: size, height: size } });
  console.log("wrote", out);
}

await renderSvg(icon, 32, resolve(pub, "favicon-32.png"));
await renderSvg(icon, 180, resolve(pub, "apple-touch-icon.png"), "#070912");
await renderSvg(icon, 512, resolve(pub, "icon-512.png"), "#070912");
await renderSvg(logo, 512, resolve(docs, "logo-512.png"));
await renderSvg(icon, 128, resolve(docs, "favicon-preview-128.png"));

// Banner / OG image
async function banner(out, w, h) {
  await page.setViewportSize({ width: w, height: h });
  let seed = 7;
  const rnd = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
  const stars = Array.from({ length: 160 }, () => {
    const x = rnd() * w, y = rnd() * h, r = rnd() * 1.2 + 0.2;
    return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r.toFixed(2)}" fill="#fff" opacity="${(rnd() * 0.6 + 0.15).toFixed(2)}"/>`;
  }).join("");
  const lockH = Math.round(h * 0.2);
  await page.setContent(`<!doctype html><html><head><style>
    @import url("${fontCss("space-grotesk", "500.css")}");
    @import url("${fontCss("space-grotesk", "700.css")}");
    body{margin:0;width:${w}px;height:${h}px;overflow:hidden;background:#06070d;font-family:'Space Grotesk',sans-serif;position:relative}
    .bg{position:absolute;inset:0;background:
      radial-gradient(ellipse 45% 70% at 82% 45%, rgba(124,92,255,.42), transparent 70%),
      radial-gradient(ellipse 30% 45% at 90% 70%, rgba(34,211,238,.22), transparent 70%),
      radial-gradient(ellipse 50% 60% at 0% 0%, rgba(124,92,255,.14), transparent 70%),
      linear-gradient(180deg,#0b0d18,#06070d)}
    .grid{position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.03) 1px,transparent 1px);background-size:48px 48px;
      -webkit-mask-image:radial-gradient(ellipse 70% 80% at 30% 40%,#000,transparent 75%)}
    svg.stars{position:absolute;inset:0}
    .mark{position:absolute;right:${w * 0.06}px;top:50%;width:${h * 0.78}px;height:${h * 0.78}px;transform:translateY(-50%);filter:drop-shadow(0 0 60px rgba(34,211,238,.35)) drop-shadow(0 0 120px rgba(124,92,255,.45))}
    .copy{position:absolute;left:${w * 0.07}px;top:50%;transform:translateY(-50%);max-width:${w * 0.52}px}
    .lock{height:${lockH}px;display:block}
    p{margin:${h * 0.05}px 0 0;color:#eef0fa;font-weight:500;font-size:${h * 0.066}px;line-height:1.15;letter-spacing:-.02em}
    p span{background:linear-gradient(95deg,#c4b5fd,#8b7cff 45%,#22d3ee);-webkit-background-clip:text;color:transparent}
    .tag{margin-top:${h * 0.05}px;display:inline-flex;gap:10px;align-items:center;padding:7px 16px;border-radius:999px;border:1px solid rgba(251,191,36,.5);background:rgba(251,191,36,.08);
      color:#fbbf24;font-size:${Math.max(13, h * 0.03)}px;letter-spacing:.14em;text-transform:uppercase;font-weight:500}
    .tag i{width:8px;height:8px;border-radius:50%;background:#fbbf24;box-shadow:0 0 10px #fbbf24}
  </style></head><body><div class="bg"></div><div class="grid"></div><svg class="stars" width="${w}" height="${h}">${stars}</svg>
  <div class="mark">${logo.replace("<svg ", '<svg width="100%" height="100%" ')}</div>
  <div class="copy">${lockup.replace("<svg ", `<svg class="lock" height="${lockH}" `)}
    <p>Trade at the <span>speed of light</span> on Stellar.</p>
    <span class="tag"><i></i>Testnet beta · unaudited</span></div></body></html>`);
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(300);
  await page.screenshot({ path: out });
  console.log("wrote", out);
}
await banner(resolve(pub, "og-image.png"), 1200, 630);
await banner(resolve(docs, "banner.png"), 1280, 400);
await browser.close();
